// Generates src/icons.generated.ts from the curated HugeIcons subset.
// Reads SVGs from repo /icons, recolors #28303F -> currentColor, keeps inner markup.
// Run: node packages/web-kit/scripts/gen-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../../../', import.meta.url)); // repo root
const ICONS = `${ROOT}icons/`;

// friendly name -> path under /icons (solid style)
const MAP = {
  home: 'interface/solid/home 02.svg',
  bell: 'interface/solid/notification 03.svg',
  user: 'interface/solid/user.svg',
  box: 'shipping and delivery/solid/package box 01.svg',
  truck: 'shipping and delivery/solid/delivery.svg',
  location: 'navigation maps/solid/location.svg',
  pin: 'navigation maps/solid/map-pin 01.svg',
  destination: 'navigation maps/solid/destination 01.svg',
  phone: 'communication/solid/call.svg',
  chat: 'communication/solid/chat.svg',
  clock: 'time and date/solid/time-oclock.svg',
  deliveryTime: 'shipping and delivery/solid/delivery-time.svg',
  chevronRight: 'arrows/solid/direction-right.svg',
  arrowLeft: 'arrows/solid/arrow-left.svg',
  plus: 'interface/solid/plus 01.svg',
  minus: 'interface/solid/minus 01.svg',
  copy: 'interface/solid/copy.svg',
  check: 'interface/solid/tick.svg',
  checkCircle: 'interface/solid/check-circle.svg',
  wallet: 'finance and payment/solid/wallet.svg',
  money: 'finance and payment/solid/money.svg',
  card: 'finance and payment/solid/card.svg',
  invoice: 'ecommerce/solid/invoice.svg',
  receipt: 'ecommerce/solid/receipt.svg',
  store: 'ecommerce/solid/store 01.svg',
  lifebuoy: 'interface/solid/lifebuoy.svg',
  star: 'interface/solid/star.svg',
  chart: 'finance and payment/solid/bar chart.svg',
  search: 'interface/solid/search 01.svg',
  bag: 'ecommerce/solid/bag 01.svg',
};

const out = {};
for (const [name, rel] of Object.entries(MAP)) {
  let svg;
  try { svg = readFileSync(ICONS + rel, 'utf8'); }
  catch { throw new Error(`Icon file missing: ${rel}`); }
  const vb = (svg.match(/viewBox="([^"]+)"/) || [, '0 0 24 24'])[1];
  const inner = svg
    .replace(/<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/#28303F/gi, 'currentColor')
    .replace(/\s+/g, ' ')
    .trim();
  out[name] = { vb, inner };
}

const body =
  '// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.\n' +
  'export type IconName = ' + Object.keys(out).map((n) => `'${n}'`).join(' | ') + ';\n' +
  'export const ICONS: Record<IconName, { vb: string; inner: string }> = ' +
  JSON.stringify(out, null, 2) + ';\n';

writeFileSync(fileURLToPath(new URL('../src/icons.generated.ts', import.meta.url)), body);
console.log(`generated ${Object.keys(out).length} icons`);
